name: Тесты

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.23', '1.24' ]

    steps:
      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Установка Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Проверка версии Go
        run: go version

      - name: Загрузка зависимостей
        run: go mod download

      - name: Запуск тестов
        run: go test -v ./...

      - name: Покрытие кода (опционально)
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...